## Import Dependencies

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/Celerates/Python/Uncleaned_DS_jobs.csv')

In [ ]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df.isna().any()

Job Title            False
Salary Estimate      False
Job Description      False
Rating               False
Company Name         False
Location             False
Headquarters         False
Size                 False
Founded              False
Type of ownership    False
Industry             False
Sector               False
dtype: bool

In [ ]:
for column in df.columns:
  print(f"========= {column} ==========")
  display(df[column].value_counts())
  print()

========= index ==========

index
0      1
451    1
443    1
444    1
445    1
      ..
225    1
226    1
227    1
228    1
671    1
Name: count, Length: 672, dtype: int64

========= Job Title ==========

Job Title
Data Scientist                                            337
Data Engineer                                              26
Senior Data Scientist                                      19
Machine Learning Engineer                                  16
Data Analyst                                               12
                                                         ...
Data Science Instructor                                     1
Business Data Analyst                                       1
Purification Scientist                                      1
Data Engineer, Enterprise Analytics                         1
AI/ML - Machine Learning Scientist, Siri Understanding      1
Name: count, Length: 172, dtype: int64

========= Salary Estimate ==========

Salary Estimate
$79K-$131K (Glassdoor est.)     32
$99K-$132K (Glassdoor est.)     32
$75K-$131K (Glassdoor est.)     32
$137K-$171K (Glassdoor est.)    30
$90K-$109K (Glassdoor est.)     30
$56K-$97K (Glassdoor est.)      22
$79K-$106K (Glassdoor est.)     22
$90K-$124K (Glassdoor est.)     22
$110K-$163K (Glassdoor est.)    21
$92K-$155K (Glassdoor est.)     21
$138K-$158K (Glassdoor est.)    21
$128K-$201K (Glassdoor est.)    21
$212K-$331K (Glassdoor est.)    21
$95K-$119K (Glassdoor est.)     21
$69K-$116K (Glassdoor est.)     21
$124K-$198K (Glassdoor est.)    21
$112K-$116K (Glassdoor est.)    21
$122K-$146K (Glassdoor est.)    21
$91K-$150K (Glassdoor est.)     21
$101K-$165K (Glassdoor est.)    21
$79K-$147K (Glassdoor est.)     20
$31K-$56K (Glassdoor est.)      20
$145K-$225K(Employer est.)      20
$141K-$225K (Glassdoor est.)    20
$66K-$112K (Glassdoor est.)     20
$80K-$132K (Glassdoor est.)     20
$87K-$141K (Glassdoor est.)     20
$105K-$167K (Glassdoor est.)    20
$79K-$133K (Glassdoor est.)     19
$71K-$123K (Glassdoor est.)     19
Name: count, dtype: int64

========= Job Description ==========

Job Description
Job Overview: The Data Scientist is a key member of our cross-functional Product team responsible for discovering new and innovative solutions to the challenges within the built environment. Now, more than ever, building owners and operators rely on Hatch Data to get a birds-eye view of asset performance to help them achieve ambitious goals around sustainable financial, environmental, and social impact. We are actively seeking an exceptional Data Scientist to help us take one of the worlds most extensive data sets for commercial building operations and transform it into amazing products for our customers.\n\nResponsibilities and Duties:\nPartner with Product Management, to Investigate high-level questions to discover new relationships between operations and outcomes\nMaintain and improve upon the accuracy and utility of existing machine-learning algorithms\nOwn the long-term Data Science Roadmap, including prototype solutions in "green field" problem spaces\nSupport ad-hoc data analysis in support of customer success and marketing efforts\nCollaborate closely with domain experts in energy and mechanical engineering, as well as with the software engineering team\nCoach and mentor others to amplify your impact and continuously demonstrate the value of data science\nExperience:\nBachelors degree in Data Science, Computer Science, Math, or related technical field.\nMinimum 3+ years experience applying data science techniques to drive product development and decision-making.\nDemonstrated track record of solving problems in industry with machine learning\nExpertise in statistical methods and experimental design and analysis\nFluent in at least one modern language for data processing (R, Python, and Scala experience ideal).\nComfortable with AWS and distributed data processing systems (e.g., Spark)\nFamiliarity with energy-efficiency, commercial building domain, regression and baseline techniques, weather normalization, etc. a plus\nExperience using APIs to manipulation and move data in and out of systems.\nMust possess outstanding written and verbal communication skills in English.\nAbility to prioritize development and operational tasks in a dynamic and challenging environment.\nAbout You:\nCare about leaving the world better than you found it.\nMission-driven and leads by example with equal parts brain and heart.\nOperationally-minded, empathetic, self-starter, driven, and gets things done.\nNatural communicator that instills confidence and trust with internal and external stakeholders.\nExcited to join a small company, with big company benefits, and upside potential.\nIdeally based in the San Francisco Bay Area.\nAbout Us:\n\nClimate change is real. Addressing this is the biggest issue of our time. While moving the world from dirty energy sources to clean ones matters, there is also an enormous opportunity to use existing resources more efficiently. Buildings consume up to 40% of the energy in North America alone. This is a big opportunity to create change. We bring our values to work and every day push to solve these problems at scale.\n\nOur team applies their knowledge of energy systems, mechanical engineering, IoT, machine learning and the built environment, to design cutting edge software that reduces the negative environmental impact of our indoor spaces while improving the bottom line for owners and operators. Our software platform has been proven across more than 400M square feet of commercial real estate with marquee customers, and were doubling down our efforts in the coming months as we prepare to accelerate growth and impact.\n\nThis is a unique opportunity to join a company that does well by doing good and is positioned for significant expansion. Youll enjoy comprehensive benefits, competitive salary, and meaningful equity. We offer a flexible work environment and the opportunity to work alongside an incredibly talented, fun, and highly motivated team.\n\nHow to Apply:\n\nDoes this sound like you? If so, please submit your resume and cover letter and provide any context you think would be helpful as we learn about you. Well be interested in understanding why youre excited about joining us, why this role seems like a perfect fit for your talents, and what success looks like for you, personally, over the next few years.                                                                                                                                                                                                                                                                                                                                                                                                                                                          12
We love programming and the excitement that comes with building something people use. We are the kind of people that love talking to users and can find the balance between solving a problem quickly and thinking about how your code will work in the future. We love to move fast, keep learning and get stuff done.\n\nOur data science team is still in its early days and you'll have a big impact on our direction and how we operate. You'll be central to researching, developing and shipping products that help our customers learn and grow from their data. For this role, we're looking for people who have developed split brains--software engineers who have become great at writing machine learning code or data scientists who have become great software developers.\n\nTechnologies we use (not comprehensive!):\nPython\n\nNumpy, Scipy, Pandas\n\nAurora, Cassandra, Kafka\n\nHTML, JavaScript, React\n\nSageMaker\n\nHow you will make a difference:\n\n\nAnalyze large data sets (we're collecting billions of individual actions every month).\nBuild products that enable our customers to grow faster and communicate more effectively with their customers.\nDevelop machine learning models and pipelines for research and production.\n\nWho You Are:\n\n\nHave experience implementing machine learning models, data pipelines and testing frameworks for research and production use.\nHave demonstrated a measurable impact based on the models you've created. It's not always easy getting a model correct, we love talking about places we got stuck and work as a team to think through ideas that could unblock us.\nHave experience processing cloud-scale data using parallel, elastic, streaming and similar techniques.\nEnjoy tuning and validating machine learning models and take a rigorous approach.\nUnderstand how to profile code and optimize performance.\nAspire to correctness (e.g. in your code, in drawing conclusions from data)\nHave a bachelor's or advanced degree in computer science, applied math, statistics or other relevant quantitative discipline, or equivalent industry experience.\n\nGet to know Klaviyo\n\nKlaviyo is the world's leading owned marketing platform known for accelerating revenue for online businesses using the channels they own like email, web, and mobile. Enabling companies to leverage these owned marketing channels, Klaviyo makes it easy to store, access, analyze and use transactional and behavioral data to power highly-targeted customer and prospect communications. And unlike other marketing platforms, Klaviyo doesn't force companies to compromise between advanced functionality or ease of use - so companies of all sizes are able to maximize their sales quickly. That's why over 28,000+ innovative companies like Unilever, Custom Ink and Eventbrite sell more with Klaviyo.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5
US Citizenship Required and (TS/SCI with FSP or CI) Required\n\nJob Description:\nExcited about data? Take action with it.\n\nAs a Phoenix Data Scientist, you'll be part of a team with access to tons of real mission and that takes action on it. You will not be simply designing algorithms or analyzing theoretical use cases. You'll be using languages like R, Python and Scala to glean actionable insights and build tangible capabilities.\n\nOn a typical day as a Phoenix Data Scientist, you'll collaborate with both engineers and mission SMEs (e.g. Cybersecurity or SIGINT analysts) to process mass amounts of data. You'll implement (not just design) neural networks, Bayesian models and other Machine Learning techniques to address mission needs.\n\nMake a difference today.\nSkills Required:\nPython or Scala\nExperience in a Linux environment\nComfortable with very large data sets\nSkills Preferred:\nR, Rstudio, Shiny\nApache Spark\nMachine Learning\nNeural Networks\nArtificial Intelligence\nPredictive Modeling\nQualifications:\nUS Citizenship Required\nSecurity Clearance (TS/SCI) Required\nSome positions require FSP\nBachelors Degree in Math, Science or Engineering\n\nBenefits Offered:\nMedical, Dental, Vision Insurance - 100% Company Paid Premiums\nSTD, LTD, and Life Insurance - 100% Company paid\n401K Automatic 10% company contribution; no matching required\nPTO - 4 weeks/year\nHolidays - 10 paid/year\nBirthdays off with pay\nReferral Bonuses Upfront AND Annually Recurring\nOpen Source Bonuses Contribute to our Github projects\nProfessional Development Paid training, Certifications and Enrichment\nABOUT PHOENIX OPERATIONS GROUP:\nPhoenix Operations Group is a high-end engineering services company dedicated to protecting and advancing our national cyber resources. As a small start-up operating out of the Baltimore/Washington DC area, we rely on innovation to continually advance our employees' skills and provide game-changing solutions to our customers.\n\nOur technical competencies include Big Data analytics (batch and streaming), Cloud Computing infrastructure, multi-INT visualization, and enterprise architectures. We support operational missions (All-Source, Financial, CND) and serve as Product Owners for our open-source research initiatives.\n\nPlease visit us at http://www.phoenix-opsgroup.com for more information.\n\nPhoenix Operations Group is an Equal Opportunity Employer. Phoenix Operations Group does not discriminate on the basis of race, religion, color, sex, gender, gender identity, sexual orientation, age, non-disqualifying physical or mental disability, national origin, veteran status or any other basis covered by appropriate law. All employment is decided on the basis of qualifications, merit, and business need.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4
Do you have a head for numbers? Like turning real-world problems into mathematical representations and checking to see if you did it right? If you like that, youll love developing algorithms with us! Our customers have some of the most interesting needs and hardest challenges to resolve. Our solutions require integrated models based on large and varied datasets, feeding analytic applications so that we can extract patterns and behaviors obscured within the data to augment the capabilities of human operators. We need both experienced and aspiring data scientists to work on all stages of the data science pipeline, to include applying existing machine learning software across large hyper-parameter trade spaces, developing new machine learning algorithms and evaluating the best the commercial AI/ML industry has to offer to our problem set.\n\nWhy Maxar?\nWe build advanced algorithms to gain analytic insights from a large range of open source and government data.\nWe enable machine learning systems, automate workflow, and design and develop custom applications for unique national-security mission.\nWe operate an end-to-end predictive analytic platform unlike any other within the US Government.\nWe provide training to expand your skills and challenges to develop them.\nOur clients missions are vital to national security, so were mission-first always.\nOur work environment is relaxed business casual.\nAt our core we believe and practice social responsibility.\nWhat would you be doing?\nExtracting and transforming data using programming languages such as Java and Python and associated open source data analytics libraries.\nAscertaining unique ways to apply algorithms to derive specific customer data analytic results.\nApplying big data analytics tools to large, diverse sets of collection data to assess risk of adverse threat activities.\nExtending existing algorithms as required to support customer requirements.\nApplying data science methods to create and optimize convolutional neural networks that will perform classification, localization and segmentation of various modalities of remotely-sensed imagery.\n\nMinimum Qualifications:\nMust be a US citizen with a current/active TS/SCI and be willing and able to obtain a CI Polygraph.\nB.S. in Engineering, Math, Physics, Computer Science or related field.\n8 years of professional experience as a Data Scientist.\nExperience with at least one of these languages: R, VBA, Java, C++, SQL, Python.\n\nDesired Qualifications:\nGraduate experience working with probabilistic and stochastic statistical analysis or computational intelligence.\nExperience conducting model feasibility research and algorithm development for machine learning.\nExperience with distributed datasets and experience analyzing both relational and NoSQL data structures.\nExperience working in an Agile environment, especially SAFe.\nAscertaining unique ways to apply algorithms to derive specific customer specific data analytics results.\nApplying big data analytics tools to large, diverse sets of collection data to assess risk of adverse threat activities.\nExtending existing algorithms as required to support customer requirements.\nExperience implementing algorithms related to machine learning.\nKnowledge of technical aspects of ISR systems.\nExperience conducting model feasibility research and algorithm development for machine learning.\nExperience developing and testing models.\nExtracting and transforming data using programming languages such as Java and Python and associated open-source data analytics libraries.\nExperience with Data Analytics.\nExceptional oral and written communications.\nOrganizational skills and excellent attention to detail.\nDevelopment experience in a Linux/Unix/Windows environment.\nCapability to work effectively in a geographically distributed development team.\nBasic systems administration and installation.\nBuild-test-deploy frameworks (Jenkins, GoCD, etc.).\nContainerization platforms (Docker, OpenShift, CloudFoundry, etc.).\nOccasional local travel to government sites for customer meetings and demonstrations.\n\n#cjpost                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              4

========= Rating ==========

Rating
 3.5    58
-1.0    50
 4.0    41
 3.3    41
 3.9    40
 3.8    39
 3.7    38
 5.0    36
 4.5    32
 3.6    31
 3.4    31
 4.2    29
 4.1    25
 4.4    24
 4.7    22
 3.2    21
 4.8    20
 4.3    14
 2.9    14
 4.6    12
 3.1    12
 4.9    11
 2.7    10
 3.0     7
 2.6     4
 2.8     3
 2.5     2
 2.2     1
 2.4     1
 2.3     1
 2.1     1
 2.0     1
Name: count, dtype: int64

========= Company Name ==========

Company Name
Hatch Data Inc                      12
Maxar Technologies\n3.5             12
Tempus Labs\n3.3                    11
AstraZeneca\n4.0                    10
Klaviyo\n4.8                         8
                                    ..
Better Hire\n4.0                     1
Rincon Research Corporation\n4.2     1
Descript\n4.3                        1
Trace Data\n3.9                      1
ChaTeck Incorporated\n5.0            1
Name: count, Length: 432, dtype: int64

========= Location ==========

Location
San Francisco, CA    69
New York, NY         50
Washington, DC       26
Boston, MA           24
Chicago, IL          22
                     ..
Oshkosh, WI           1
Culver City, CA       1
Lake Oswego, OR       1
New Orleans, LA       1
Irwindale, CA         1
Name: count, Length: 207, dtype: int64

========= Headquarters ==========

Headquarters
New York, NY         33
-1                   31
San Francisco, CA    31
Chicago, IL          23
Boston, MA           19
                     ..
Irving, TX            1
Scottsdale, AZ        1
Greensboro, NC        1
Newark, CA            1
Fort Lee, NJ          1
Name: count, Length: 229, dtype: int64

========= Size ==========

Size
51 to 200 employees        135
1001 to 5000 employees     104
1 to 50 employees           86
201 to 500 employees        85
10000+ employees            80
501 to 1000 employees       77
5001 to 10000 employees     61
-1                          27
Unknown                     17
Name: count, dtype: int64

========= Founded ==========

Founded
-1       118
 2012     34
 2011     25
 2015     22
 2010     22
        ...
 1820      1
 1952      1
 1959      1
 1894      1
 1962      1
Name: count, Length: 103, dtype: int64

========= Type of ownership ==========

Type of ownership
Company - Private                 397
Company - Public                  153
Nonprofit Organization             36
Subsidiary or Business Segment     28
-1                                 27
Government                         10
Other Organization                  5
Private Practice / Firm             4
Unknown                             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64

========= Industry ==========

Industry
-1                                          71
Biotech & Pharmaceuticals                   66
IT Services                                 61
Computer Hardware & Software                57
Aerospace & Defense                         46
Enterprise Software & Network Solutions     43
Consulting                                  38
Staffing & Outsourcing                      36
Insurance Carriers                          28
Internet                                    27
Advertising & Marketing                     23
Health Care Services & Hospitals            21
Research & Development                      17
Federal Agencies                            16
Investment Banking & Asset Management       13
Banks & Credit Unions                        8
Lending                                      8
Energy                                       5
Consumer Products Manufacturing              5
Telecommunications Services                  5
Insurance Agencies & Brokerages              4
Food & Beverage Manufacturing                4
Utilities                                    3
Electrical & Electronic Manufacturing        3
Colleges & Universities                      3
Other Retail Stores                          3
Architectural & Engineering Services         3
Chemical Manufacturing                       3
Real Estate                                  3
Miscellaneous Manufacturing                  3
Accounting                                   3
Wholesale                                    3
Industrial Manufacturing                     3
Video Games                                  3
Travel Agencies                              2
Express Delivery Services                    2
Timber Operations                            2
Financial Transaction Processing             2
Construction                                 2
Health, Beauty, & Fitness                    2
Transportation Equipment Manufacturing       2
Oil & Gas Services                           2
Venture Capital & Private Equity             2
Consumer Electronics & Appliances Stores     2
Department, Clothing, & Shoe Stores          1
Publishing                                   1
Social Assistance                            1
Farm Support Services                        1
Logistics & Supply Chain                     1
Transportation Management                    1
State & Regional Agencies                    1
Hotels, Motels, & Resorts                    1
Food & Beverage Stores                       1
News Outlet                                  1
Telecommunications Manufacturing             1
Cable, Internet & Telephone Providers        1
Shipping                                     1
Rail                                         1
Name: count, dtype: int64

========= Sector ==========

Sector
Information Technology                188
Business Services                     120
-1                                     71
Biotech & Pharmaceuticals              66
Aerospace & Defense                    46
Finance                                33
Insurance                              32
Manufacturing                          23
Health Care                            21
Government                             17
Oil, Gas, Energy & Utilities           10
Retail                                  7
Telecommunications                      7
Transportation & Logistics              6
Media                                   5
Real Estate                             3
Travel & Tourism                        3
Agriculture & Forestry                  3
Education                               3
Accounting & Legal                      3
Construction, Repair & Maintenance      2
Consumer Services                       2
Non-Profit                              1
Name: count, dtype: int64

========= Revenue ==========

Revenue
Unknown / Non-Applicable            213
$100 to $500 million (USD)           94
$10+ billion (USD)                   63
$2 to $5 billion (USD)               45
$10 to $25 million (USD)             41
$1 to $2 billion (USD)               36
$25 to $50 million (USD)             36
$50 to $100 million (USD)            31
$1 to $5 million (USD)               31
-1                                   27
$500 million to $1 billion (USD)     19
$5 to $10 million (USD)              14
Less than $1 million (USD)           14
$5 to $10 billion (USD)               8
Name: count, dtype: int64

========= Competitors ==========

Competitors
-1                                                                501
Roche, GlaxoSmithKline, Novartis                                   10
Los Alamos National Laboratory, Battelle, SRI International         6
Leidos, CACI International, Booz Allen Hamilton                     6
MIT Lincoln Laboratory, Lockheed Martin, Northrop Grumman           3
                                                                 ...
Pfizer, GlaxoSmithKline                                             1
Square, Amazon, Apple                                               1
Lumentum Operations, Keysight Technologies, O-Net Technologies      1
Munich Re, Hannover RE, SCOR                                        1
Genomic Health, Myriad Genetics, The Broad Institute                1
Name: count, Length: 108, dtype: int64

From the code above, we save that there are also other missing value besides -1 in several column. Below is the list of all missing values for each of the columns:

- Rating : -1
- Hearquarters : -1
- Size : -1, Unknown
- Founded : -1
- Type of Ownership : -1, Unknown
- Industry : -1
- Sector : -1
- Revenue : -1, Unknown / Non-Applicable
- Competitors : -1

First we have to see whats the percentage of missing value in that column. If it contained a lot of missing value (lets say >35%), then we can just drop that column. If not, then we can impute it.

In [ ]:
(len(df[df['Rating']==-1])/len(df))*100

7.440476190476191

In [ ]:
(len(df[df['Headquarters']=="-1"])/len(df))*100

4.613095238095238

In [ ]:
(len(df[df['Size'].isin(["-1", "Unknown"])])/len(df))*100

6.547619047619048

In [ ]:
(len(df[df['Founded']==-1])/len(df))*100

17.559523809523807

In [ ]:
(len(df[df['Type of ownership'].isin(["-1", "Unknown"])])/len(df))*100

4.613095238095238

In [ ]:
(len(df[df['Industry']=="-1"])/len(df))*100

10.56547619047619

In [ ]:
(len(df[df['Sector']=="-1"])/len(df))*100

10.56547619047619

In [ ]:
(len(df[df['Revenue'].isin(["-1", "Unknown / Non-Applicable"])])/len(df))*100

35.714285714285715

In [ ]:
(len(df[df['Competitors']=="-1"])/len(df))*100

74.55357142857143

In [ ]:
df = df.drop(columns=['index', 'Revenue', 'Competitors'])

In [ ]:
df.head(5)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services
2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services
3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing
4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services

In [ ]:
# Mean imputation on Rating Column

avg_rating = df[df['Rating'] != -1]['Rating'].mean()

df['Rating'] = df['Rating'].apply(lambda x: avg_rating if x==-1 else x)

In [ ]:
# Mode imputation on Headquarters columns

mode_hq = df[df['Headquarters'] != '-1']['Headquarters'].mode()[0]

df['Headquarters'] = df['Headquarters'].apply(lambda x: mode_hq if x=="-1" else x)

In [ ]:
# Mode imputation on Size columns

mode_size = df[~df['Size'].isin(['-1','Unknown'])]['Size'].mode()[0]

df['Size'] = df['Size'].apply(lambda x: mode_size if x in ["-1", 'Unknown'] else x)

In [ ]:
# Mode imputation on Founded columns

mode_found = df[df['Founded'] != -1]['Founded'].mode()[0]

df['Founded'] = df['Founded'].apply(lambda x: mode_found if x==-1 else x)

In [ ]:
# Mode imputation on Type of ownership columns

mode_type = df[~df['Type of ownership'].isin(['-1','Unknown'])]['Type of ownership'].mode()[0]

df['Type of ownership'] = df['Type of ownership'].apply(lambda x: mode_type if x in ["-1", 'Unknown'] else x)

In [ ]:
# Mode imputation on Industry columns

mode_ind = df[df['Industry'] != '-1']['Industry'].mode()[0]

df['Industry'] = df['Industry'].apply(lambda x: mode_ind if x=="-1" else x)

In [ ]:
# Mode imputation on Sector columns

mode_sec = df[df['Sector'] != '-1']['Sector'].mode()[0]

df['Sector'] = df['Sector'].apply(lambda x: mode_sec if x=="-1" else x)

In [ ]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services
2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.800000,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services
3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing
4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services
...,...,...,...,...,...,...,...,...,...,...,...,...
667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.600000,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services
668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,3.881833,JKGT,"San Francisco, CA","New York, NY",51 to 200 employees,2012,Company - Private,Biotech & Pharmaceuticals,Information Technology
669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,3.881833,AccessHope,"Irwindale, CA","New York, NY",51 to 200 employees,2012,Company - Private,Biotech & Pharmaceuticals,Information Technology
670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.000000,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,2012,Company - Private,Advertising & Marketing,Business Services
671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services

## Categorical Data Encoding

Categorical data encoding is the process of converting categorical variables into a format that can be used for machine learning models. Categorical variables are those that represent categories or groups, such as "red," "blue," "green" for a color variable or "male" and "female" for a gender variable. There are many ways to encode your categorical data, below are the encoding strategy that are often used in practice:

1. One-Hot Encoding
2. Label Encoding or Ordinal Encoding
3. Target Encoding

### One-Hot Encoding

In [ ]:
dummies = pd.get_dummies(df['Size'])

dummies = dummies.apply(lambda x: x.map({False: 0, True: 1}))
dummies

,1 to 50 employees,10000+ employees,1001 to 5000 employees,201 to 500 employees,5001 to 10000 employees,501 to 1000 employees,51 to 200 employees
0,0,0,1,0,0,0,0
1,0,0,0,0,1,0,0
2,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0
4,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...
667,0,0,1,0,0,0,0
668,0,0,0,0,0,0,1
669,0,0,0,0,0,0,1
670,1,0,0,0,0,0,0
671,0,0,1,0,0,0,0

### Label Encoding

In [ ]:
def label_encoding_size_col(x):
  if x == '1 to 50 employees':
    return 0
  elif x == '51 to 200 employees':
    return 1
  elif x == '201 to 500 employees':
    return 2
  elif x == '501 to 1000 employees':
    return 3
  elif x == '1001 to 5000 employees':
    return 4
  elif x == '5001 to 10000 employees':
    return 5
  else:
    return 6

In [ ]:
df['Size'].apply(label_encoding_size_col)

0      4
1      5
2      4
3      3
4      1
      ..
667    4
668    1
669    1
670    0
671    4
Name: Size, Length: 672, dtype: int64

In [ ]:
# from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
# import pandas as pd

# # Sample data
# data = {'size': ['small', 'medium', 'large', 'small', 'large', 'medium']}
# df = pd.DataFrame(data)

# # Ordinal Encoding
# ordinal_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']], dtype=int)
# ordinal_encoded = ordinal_encoder.fit_transform(df[['size']])
# print("Ordinal Encoded:")
# print(ordinal_encoded)

# # Label Encoding
# label_encoder = LabelEncoder()
# label_encoded = label_encoder.fit_transform(df['size'])
# print("\nLabel Encoded:")
# print(label_encoded)

### Target Encoding

Target encoding, also known as mean encoding or likelihood encoding, is a method of encoding categorical variables where each category is replaced with the average value of the target variable for that category.

![WhatsApp Image 2024-04-22 at 11.33.29.jpeg]()

https://www.kaggle.com/code/caesarlupum/catcomp-simple-target-encoding

## Others Cleaning
Last but not least, we can clean other stuff on our dataset as well e.g. normalize text column value

### Job Title

In [ ]:
df['Job Title'].value_counts().head(50)

Job Title
Data Scientist                                                                                      337
Data Engineer                                                                                        26
Senior Data Scientist                                                                                19
Machine Learning Engineer                                                                            16
Data Analyst                                                                                         12
Senior Data Analyst                                                                                   6
Senior Data Engineer                                                                                  5
Data Science Software Engineer                                                                        4
ENGINEER - COMPUTER SCIENTIST - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING - SAN ANTONIO OR      4
Data Scientist - TS/SCI FSP or CI Required                                                            4
Principal Data Scientist                                                                              3
Sr. ML/Data Scientist - AI/NLP/Chatbot                                                                3
AI Ops Data Scientist                                                                                 3
Data Modeler (Analytical Systems)                                                                     3
Lead Data Scientist                                                                                   3
Senior Machine Learning Scientist - Bay Area, CA                                                      3
Decision Scientist                                                                                    3
Senior Business Intelligence Analyst                                                                  3
Data Scientist - TS/SCI Required                                                                      3
Analytics - Business Assurance Data Analyst                                                           3
Senior Data Scientist – Image Analytics, Novartis AI Innovation Lab                                   3
In-Line Inspection Data Analyst                                                                       2
Applied Computer Scientist                                                                            2
Data Scientist(s)/Machine Learning Engineer                                                           2
Senior Data Scientist - R&D Oncology                                                                  2
Principal Machine Learning Scientist                                                                  2
Principal Data Scientist - Machine Learning                                                           2
Computational Behavioral Scientist                                                                    2
Sr. Data Scientist II                                                                                 2
Research Scientist - Patient-Centered Research (Remote)                                               2
Scientist / Group Lead, Cancer Biology                                                                2
Principal Scientist/Associate Director, Quality Control and Analytical Technologies                   2
Intelligence Data Analyst, Senior                                                                     2
Weapons and Sensors Engineer/Scientist                                                                2
Scientist - Machine Learning                                                                          2
Data Scientist (TS/SCI w/ Poly)                                                                       2
Computer Vision / Deep Learning Scientist                                                             2
IT Partner Digital Health Technology and Data Science                                                 2
Senior Data Analyst - Finance & Platform Analytics                                                    2
Data Engineer (Analytics, SQL, Python, AWS)                                                           2
Sr. Data Scientist                                                                                    2
Cloud Data Engineer (Azure)                                                                           2
Analytics Manager - Data Mart                                                                         2
Data Engineer - Kafka                                                                                 2
VP, Data Science                                                                                      2
Senior Scientist - Toxicologist - Product Integrity (Stewardship)                                     2
Senior Machine Learning Engineer                                                                      2
Data Analyst - Unilever Prestige                                                                      2
Machine Learning Engineer/Scientist                                                                   2
Sr Data Scientist                                                                                     2
Name: count, dtype: int64

In [ ]:
def clean_job_title(x):
  if 'data scientist' in x.lower():
    return 'Data Scientist'
  elif 'data engineer' in x.lower():
    return 'Data Engineer'
  elif 'machine learning engineer' in x.lower():
    return 'ML Engineer'
  elif 'data analyst' in x.lower():
    return 'Data Analyst'
  elif 'machine learning scientist' in x.lower():
    return 'ML Scientist'
  elif 'business intelligence' in x.lower():
    return 'Business Intelligence'
  elif 'research scientist' in x.lower():
    return 'Research Scientist'
  elif 'data science manager' in x.lower():
    return 'Data Science Manager'
  else:
    return 'Others'

In [ ]:
df['Job Title'] = df['Job Title'].apply(clean_job_title)

df['Job Title'].value_counts()

Job Title
Data Scientist           455
Others                    79
Data Analyst              47
Data Engineer             47
ML Engineer               21
ML Scientist              11
Business Intelligence      6
Research Scientist         4
Data Science Manager       2
Name: count, dtype: int64

### Salary Estimate

In [ ]:
df['Salary Estimate'].value_counts()

Salary Estimate
$79K-$131K (Glassdoor est.)     32
$99K-$132K (Glassdoor est.)     32
$75K-$131K (Glassdoor est.)     32
$137K-$171K (Glassdoor est.)    30
$90K-$109K (Glassdoor est.)     30
$56K-$97K (Glassdoor est.)      22
$79K-$106K (Glassdoor est.)     22
$90K-$124K (Glassdoor est.)     22
$110K-$163K (Glassdoor est.)    21
$92K-$155K (Glassdoor est.)     21
$138K-$158K (Glassdoor est.)    21
$128K-$201K (Glassdoor est.)    21
$212K-$331K (Glassdoor est.)    21
$95K-$119K (Glassdoor est.)     21
$69K-$116K (Glassdoor est.)     21
$124K-$198K (Glassdoor est.)    21
$112K-$116K (Glassdoor est.)    21
$122K-$146K (Glassdoor est.)    21
$91K-$150K (Glassdoor est.)     21
$101K-$165K (Glassdoor est.)    21
$79K-$147K (Glassdoor est.)     20
$31K-$56K (Glassdoor est.)      20
$145K-$225K(Employer est.)      20
$141K-$225K (Glassdoor est.)    20
$66K-$112K (Glassdoor est.)     20
$80K-$132K (Glassdoor est.)     20
$87K-$141K (Glassdoor est.)     20
$105K-$167K (Glassdoor est.)    20
$79K-$133K (Glassdoor est.)     19
$71K-$123K (Glassdoor est.)     19
Name: count, dtype: int64

In [ ]:
def get_mean_salary(text):
  '''
    function to extract the mean of salary range
  '''
  numb = re.findall(r'[0-9]+', text) #get all numbers in pandas series
  numb = [int(x) for x in numb]
  return np.mean(numb) * 1000

In [ ]:
df['Salary Estimate'] = df['Salary Estimate'].apply(get_mean_salary)

df['Salary Estimate'].value_counts()

Salary Estimate
92500.0     43
107000.0    43
114000.0    41
106000.0    39
103000.0    32
105000.0    32
115500.0    32
154000.0    30
99500.0     30
76500.0     22
161000.0    21
136500.0    21
134000.0    21
120500.0    21
164500.0    21
148000.0    21
271500.0    21
123500.0    21
133000.0    21
89000.0     20
113000.0    20
43500.0     20
185000.0    20
183000.0    20
136000.0    20
97000.0     19
Name: count, dtype: int64

### Company Name

In [ ]:
df['Company Name']

0               Healthfirst\n3.1
1                   ManTech\n4.2
2            Analysis Group\n3.8
3                   INFICON\n3.5
4        Affinity Solutions\n2.9
                 ...
667                TRANZACT\n3.6
668                         JKGT
669                   AccessHope
670    ChaTeck Incorporated\n5.0
671           1-800-Flowers\n2.7
Name: Company Name, Length: 672, dtype: object

In [ ]:
df['Company Name'] = df['Company Name'].apply(lambda x: x.split('\n')[0])

df['Company Name']

0               Healthfirst
1                   ManTech
2            Analysis Group
3                   INFICON
4        Affinity Solutions
               ...
667                TRANZACT
668                    JKGT
669              AccessHope
670    ChaTeck Incorporated
671           1-800-Flowers
Name: Company Name, Length: 672, dtype: object

## Final Cleaned Data

In [ ]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector
0,Data Scientist,154000.0,Description\n\nThe Senior Data Scientist is re...,3.100000,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance
1,Data Scientist,154000.0,"Secure our Nation, Ignite your Future\n\nJoin ...",4.200000,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services
2,Data Scientist,154000.0,Overview\n\n\nAnalysis Group is one of the lar...,3.800000,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services
3,Data Scientist,154000.0,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.500000,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing
4,Data Scientist,154000.0,Data Scientist\nAffinity Solutions / Marketing...,2.900000,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services
...,...,...,...,...,...,...,...,...,...,...,...,...
667,Data Scientist,136000.0,Summary\n\nWe’re looking for a data scientist ...,3.600000,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services
668,Data Scientist,136000.0,Job Description\nBecome a thought leader withi...,3.881833,JKGT,"San Francisco, CA","New York, NY",51 to 200 employees,2012,Company - Private,Biotech & Pharmaceuticals,Information Technology
669,Data Scientist,136000.0,Join a thriving company that is changing the w...,3.881833,AccessHope,"Irwindale, CA","New York, NY",51 to 200 employees,2012,Company - Private,Biotech & Pharmaceuticals,Information Technology
670,Data Scientist,136000.0,100 Remote Opportunity As an AINLP Data Scient...,5.000000,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,2012,Company - Private,Advertising & Marketing,Business Services
671,Data Scientist,136000.0,Description\n\nThe Data Scientist will be part...,2.700000,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services

## Save Cleaned Data

In [ ]:
df.to_csv('Cleaned_DS_jobs.csv', index=False)